### ISSUE TITLE
Not recieving websocket messages after connection reset

### ISSUE THREAD

**Issue by sivagontla** [wuhewuhe/bybit-java-api#47]
Once websocket connection gets reset, no longer receiving "pong" messages and subsequent position/order websocket updates.
It is clear via logs that once the connection reset happens, we no longer get "pong" messages. Using 1.1.4.

23:18:54.089 [thread-private-ping] INFO  c.b.a.c.w.WebsocketClientImpl - {"op":"ping"}
Handle message :{"op":"pong","args":["1703891934111"],"conn_id":"cldfliof2tdvgsflmepg-per1z"}
23:19:14.089 [thread-private-ping] INFO  c.b.a.c.w.WebsocketClientImpl - {"op":"ping"}
Handle message :{"op":"pong","args":["1703891954111"],"conn_id":"cldfliof2tdvgsflmepg-per1z"}
23:19:34.089 [thread-private-ping] INFO  c.b.a.c.w.WebsocketClientImpl - {"op":"ping"}
Handle message :{"op":"pong","args":["1703891974111"],"conn_id":"cldfliof2tdvgsflmepg-per1z"}
23:19:54.089 [thread-private-ping] INFO  c.b.a.c.w.WebsocketClientImpl - {"op":"ping"}
23:19:54.091 [OkHttp https://stream.bybit.com/...] ERROR c.b.a.c.w.WebsocketClientImpl - Connection reset
23:20:14.090 [thread-private-ping] INFO  c.b.a.c.w.WebsocketClientImpl - {"op":"ping"}
23:20:34.090 [thread-private-ping] INFO  c.b.a.c.w.WebsocketClientImpl - {"op":"ping"}
23:20:54.090 [thread-private-ping] INFO  c.b.a.c.w.WebsocketClientImpl - {"op":"ping"}
23:21:14.090 [thread-private-ping] INFO  c.b.a.c.w.WebsocketClientImpl - {"op":"ping"}

**Comment by wuhewuhe** [comment]
please use 1.2.5
